# Generated by Django 5.1 on 2024-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdata',
            name='csv_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
